### ISSUE TITLE
Linux / Ubuntu Version?

### ISSUE THREAD

**Issue by rickmurt** [shopifypartners/developer-tools#1]
Hi there,

If I recall correctly, at the pop-up talk at Unite, someone had mentioned that this was an electron app. Any chance of a linux / ubuntu version? 

Thanks!

**Comment by jcalazan** [comment]
+1 for Linux/Ubuntu support! :)

**Comment by wadtech** [comment]
If you're going to remove the web version of this tool at least make the replacement cross-platform...

**Comment by nikegp** [comment]
It was SO useful for app development

**Comment by adamshields** [comment]
I would like a  windows version as well

**Comment by tylerball** [comment]
We don't currently have plans to release a windows or Linux version of this tool, but I encourage you to try the beta of the [Shopify App CLI](https://github.com/Shopify/shopify-app-cli/), which works in Windows via WSL and Linux.
