### ISSUE TITLE
How to uninstall the app?

### ISSUE THREAD

**Issue by jasontll** [shopifypartners/developer-tools#22]
The app stopped working suddenly and I was trying to reinstall it. But I cannot remove all the setting.
Any help?

**Comment by devshahani** [comment]
hey @jasontll, you can clear all app data by deleting the `Shopify Developer Tools` folder in:
`Macintosh HD⁩ ▸ ⁨Users⁩ ▸ ⁨{your-user-name} ▸ ⁨Library⁩ ▸ ⁨Application Support⁩`
