### ISSUE TITLE
Windows users?

### ISSUE THREAD

**Issue by Shine18** [shopifypartners/developer-tools#25]
Have you guys ever thought about windows users when releasing any developer tool?

**Comment by tylerball** [comment]
We don't currently have plans to release a windows version of this tool, but I encourage you to try the beta of the [Shopify App CLI](https://github.com/Shopify/shopify-app-cli/), which works in Windows via WSL.

**Comment by Shine18** [comment]
Well, Thanks for being so unsupportable to windows. 
BTW, I already know about the CLI
