### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by red2678** [shopifypartners/developer-tools#8]
Please offer support for windows.

**Comment by lyongdee** [comment]
me too.

**Comment by rmbadaro** [comment]
Is there any tool for Windows?

**Comment by anjagusev** [comment]
Yes please. At Unite it was mentioned that the developer tools will be released for Windows. Is this still on the roadmap?

**Comment by rickysychan** [comment]
PLEASE I NEED THIS ON WINDOWS!!!!!

**Comment by internationalhouseofdonald** [comment]
Following

**Comment by Blanen** [comment]
It's a sad joke it doesn't.

First the data generator app tells me it's not in service anymore and you need to install the Developer tools app. Then THAT tells me to it's out of service and I need to install the desktop app. And then THAT tells me it's only for Mac OS.

You guys are a web tech company, the least you could've done is make it in electron and instantly have cross platform.

**Comment by anjagusev** [comment]
> You guys are a web tech company, the least you could've done is make it in electron and instantly have cross platform.

@Blanen actually, the developer-tools app is built in Electron. From my understanding, they just never took the time to release the Windows version.

**Comment by jessicalynnepruitt** [comment]
I contacted support today, and there are still no Windows OS Developer Tools available. They told me to go here and submit an issue. Ugh Most coders I know use Windows, what are they waiting for?!?

**Comment by red2678** [comment]
This repo is no longer maintained, so this "feature" will never be implemented. You should use the Shopify CLI.

https://github.com/Shopify/shopify-app-cli/

**Comment by jessicalynnepruitt** [comment]
I’ll check it out. Thanks!

For God’s glory,

Jessica Pruitt
(Sent from my iPhone)
